version: '3'
services:

  # traefik:
  #   build:
  #     context: ../../builds/traefik
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - admin-panel
  #   # volumes:
  #   #   - traefik:/etc/traefik/acme:z
  #   ports:
  #     - "0.0.0.0:80:80"

  payments-service: &nest
    build:
      context: ../../builds/nest-cli
      dockerfile: ./Dockerfile
    entrypoint: yarn
    command: run start:debug
    ports:
      - 3000:3000
    volumes:
      - ../../src/payments-service:/app

  auth-service: 
    <<: *nest
    ports:
      - 3001:3000
    volumes:
      - ../../src/auth-service:/app

  admin-panel: &angular
    build:
      context: ../../builds/angular-cli
      dockerfile: ./Dockerfile
    command: start 
    scale: 1
    entrypoint: npm
    ports:
      - 4200:4200
    volumes:
      - ../../src/admin-panel:/app

  payments-service-mongo: 
    build:
      context: ../../builds/mongo
      dockerfile: ./Dockerfile
    volumes:
      - ../../data/payments-service-mongo:/data/db


  auth-service-mongo: 
    build:
      context: ../../builds/mongo
      dockerfile: ./Dockerfile
    volumes:
      - ../../data/auth-service-mongo:/data/db

  redis: 
    build:
      context: ../../builds/redis
      dockerfile: ./Dockerfile
    # volumes:
    #   - ../../data/redis:/data/db

  # spring-boot: 
  #   build:
  #     context: ../../builds/springboot
  #     dockerfile: ./Dockerfile
