version: '3'
services:

  spring-boot: 
    build:
      context: ../../builds/springboot
      dockerfile: ./Dockerfile
    volumes:
        - ../../src/spring-back:/opt/app
    ports:
        - 8080:8080