log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":4200"
    http:
      redirections:
        entryPoint:
          to: web-secure
http:
  routers:
    web-router:
      # rule: "Host(`api.dominio.io`)"
      entryPoints:
        - web-secure
      service: admin-panel

  services:
    admin-panel:
      loadBalancer:
        servers:
          - url: http://admin-panel

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
